name: ${project.artifactId}
version:  ${project.version}
main: com.xenojava.tournament.bukkit.TournamentPlugin
author: XenoJava
website: www.xenojava.com
description: 
         A project developed for and only Triangle. This project
         was all made possible by the plugin developer and requester!
